version: '3.8'

services:
  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5094:8080"
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    volumes:
      - app-data:/app/volumes

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
